---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: oracle-solaris-11
    driver:
      box: oracle-solaris-11
      box_url: https://vagrantcloud.com/ruby-concurrency/oracle-solaris-11/version/1/provider/virtualbox.box
  - name: smartos
    driver:
      box: livinginthepast/smartos-base64
      vagrantfile_erb: test/templates/Vagrantfile.smartos.erb
    provisioner:
      name: chef_zero
      require_chef_omnibus: true
      sudo: true
      chef_omnibus_url: https://raw.github.com/wanelo-chef/chef-bootstrap/master/system.sh

suites:
  - name: install
    run_list:
      - recipe[test_smf::smf_install]
      - recipe[test_smf::smf_solaris_testing]
    attributes:
