name             'smf'
maintainer       'Nordstrom, Inc.'
maintainer_email 'CHANGE_ME_TO_SOMETHING_APPROPRIATE@nordstrom.com'
license          'All rights reserved'
description      'Installs/Configures smf'
long_description 'Longer version of description: Installs/Configures smf'
version          '0.0.0'
